# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  watch:
    types: [ started ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora
    steps:
      - name: ex3
        run:
          echo /etc/os-release
